### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by FloEdelmann** [lukasleist/news-chrome-notifier#7]
I'm currently in the process of switching from Feedly to Nextcloud News. On Firefox, I was using the [Feedly-Notifier](https://github.com/olsh/Feedly-Notifier) extension to keep track of unread articles. It seems like there is no available alternative supporting Nextcloud News on Firefox.

I now tried your Chrome extension and it works great, but unfortunately it is not available for Firefox.
[Porting it to work on Firefox](https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/) might be possible without too much work. Would you consider that?

**Comment by FloEdelmann** [comment]
The result of the the automatic [Extension Compatibility Test](https://www.extensiontest.com/):

> Great news! Your extension is compatible with Firefox.

<details>
<summary>Details</summary>

```json
{
  "compat": [],
  "errors": [
    {
      "message": "\"/manifest_version\" must be <= 2",
      "description": "Your JSON file could not be parsed.",
      "locations": [
        {}
      ]
    },
    {
      "message": "\"/background\" is in an unsupported format.",
      "description": "\"/background\" is in an unsupported format.",
      "locations": [
        {
          "file": "manifest.json"
        }
      ]
    },
    {
      "message": "The extension ID is required in Manifest Version 3 and above.",
      "description": "See https://mzl.la/3PLZYdo for more information.",
      "locations": [
        {
          "file": "manifest.json"
        }
      ]
    }
  ],
  "warnings": [
    {
      "message": "Unsafe assignment to innerHTML",
      "description": "Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.",
      "locations": [
        {
          "file": "filters.js",
          "line": 5
        },
        {
          "file": "filters.js",
          "line": 312
        }
      ]
    },
    {
      "message": "The Function constructor is eval.",
      "description": "Evaluation of strings as code can lead to security vulnerabilities and performance issues, even in the most innocuous of circumstances. Please avoid using `eval` and the `Function` constructor when at all possible.'",
      "locations": [
        {
          "file": "options/options.js",
          "line": 1
        },
        {
          "file": "options/options.js",
          "line": 3
        }
      ]
    }
  ]
}
```

</details>

**Comment by lukasleist** [comment]
I am currently working on a firefox version, the layout still requires some tweaks to look correct in firefox.

**Comment by lukasleist** [comment]
I added a Firefox-Version that is available from the [Firefox Add-On Store](https://addons.mozilla.org/de/firefox/addon/nextcloud-news-webextension/) or the release page, feel free to check it out.

**Comment by FloEdelmann** [comment]
Really cool, thanks! I just downloaded it and at first glance it looks pretty good :slightly_smiling_face: 

I will report feedback as separate issues in the coming days.
